### ISSUE TITLE
Causes Battlefront II (2017) to completely not start up.

### ISSUE THREAD

**Issue by LoganRilling** [Dulana57/FrostyFix#1]
I have no idea what's happened as I am not familiar with this code.  I used this with the Gamepass Ultimate version of EA Desktop because I could not get mods loaded in and I've been desperately trying to figure out what's wrong. After using this with battlefront II it does not start up from anything. Not with FMM, not with Xbox, not with EA Desktop, not directly from the file. I've tried deleting the game, EA Desktop, and FrostyFix, but it was to no avail. I have no idea what it did. Please look into this.

**Comment by Dulana57** [comment]
Check your environment variables, all frostyfix does is add a variable called GAME_DATA_DIR. You can manually delete it and it would undo anything frostyfix has done
