### ISSUE TITLE
Absolutely doesn't work with MEC and can no longer start it up

### ISSUE THREAD

**Issue by yahomeboyprophet** [Dulana57/FrostyFix#2]
I've been troubleshooting FMM no longer working with MEC for over a year now and beside this not working it causes MEC to not be started normally which is obviously problematic

I have MEC on Steam

**Comment by Dulana57** [comment]
What game is MEC?

**Comment by Dulana57** [comment]
Idk what standard procedure but ill close this cause it needs more info

**Comment by 78Alpha** [comment]
That would be Mirror's Edge Catalyst.

Attempting to use Frosty Fix or FMM leads to a broken installation of MEC. And judging by google results, this has been an ongoing issue for a year or 2.
